import { Space } from '../types';

export const SPACES: Space[] = [
  {
    id: 'dramaselebriti',
    name: 'Drama Selebriti',
    slug: 'dramaselebriti',
    description: "Gosip, drama, dan hot take soal selebriti & influencer Indonesia.",
    avatar_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=400&fit=crop',
    members_count: 524000,
    posts_count: 18900,
    created_at: '2024-03-15',
    rules: [
      'Gosip hanya untuk figur publik, bukan warga biasa',
      'Dilarang doxxing atau menyebut alamat pribadi',
      'Beri label opini vs fakta dengan jelas',
      'Meme dan humor diperbolehkan, tapi jangan bully personal',
    ],
  },
  {
    id: 'jakartavibes',
    name: 'Jakarta Vibes',
    slug: 'jakartavibes',
    description: "Kehidupan Jakarta: macet, kuliner, nightlife, dan survival guide.",
    avatar_url: 'https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&h=400&fit=crop',
    members_count: 312000,
    posts_count: 14200,
    created_at: '2024-01-20',
    rules: [
      'Sharing pengalaman nyata, bukan hoax atau isu tidak jelas',
      'Rekomendasi tempat wajib disertai nama lokasi',
      'Dilarang spam promosi bisnis',
      'Saling bantu sesama warga Jakarta',
    ],
  },
  {
    id: 'politiksantai',
    name: 'Politik Santai',
    slug: 'politiksantai',
    description: "Ngomongin politik tanpa ribut. Diskusi santai, meme boleh.",
    avatar_url: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=400&fit=crop',
    members_count: 278000,
    posts_count: 9800,
    created_at: '2024-06-10',
    rules: [
      'Diskusi berdasarkan data dan fakta, bukan asumsi',
      'Dilarang fitnah dan berita hoax',
      'Hormati pendapat berbeda, debat boleh tapi tetap sopan',
      'Dilarang kampanye partai atau kandidat secara eksplisit',
      'Tetap santun walau beda pandangan politik',
    ],
  },
  {
    id: 'kuliner',
    name: 'Kuliner Nusantara',
    slug: 'kulinernusantara',
    description: "Review makanan, rekomendasi tempat makan, dan perang rendang vs gudeg.",
    avatar_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=400&fit=crop',
    members_count: 445000,
    posts_count: 21000,
    created_at: '2023-11-05',
    rules: [
      'Review jujur berdasarkan pengalaman nyata',
      'Sertakan foto makanan kalau bisa',
      'Tulis nama tempat dan lokasi lengkap untuk rekomendasi',
      'Dilarang promosi berbayar tanpa label #sponsored',
    ],
  },
  {
    id: 'devid',
    name: 'Dev Indonesia',
    slug: 'devindonesia',
    description: "Komunitas developer Indonesia. Curhat koding, lowongan kerja, dan meme programming.",
    avatar_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop',
    members_count: 156000,
    posts_count: 12400,
    created_at: '2024-02-28',
    rules: [
      'Pertanyaan teknis wajib disertai kode dan pesan error',
      'Gunakan code block untuk snippet kode',
      'Dilarang repost lowongan kerja tanpa izin moderator',
      'Saling bantu, bukan saling menjatuhkan',
      'Hargai semua level pengalaman, dari junior sampai senior',
    ],
  },
  {
    id: 'startupid',
    name: 'Startup Indonesia',
    slug: 'startupindonesia',
    description: "Ngobrol soal startup, funding, dan hustle culture ala Jakarta.",
    avatar_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=400&fit=crop',
    members_count: 89000,
    posts_count: 6700,
    created_at: '2024-08-12',
    rules: [
      'Dilarang cold pitch tanpa izin komunitas',
      'Sharing pengalaman nyata dan lessons learned',
      'Kritik boleh, tapi konstruktif dan berbasis fakta',
      'Dilarang spam link fundraising atau referral',
    ],
  },
  {
    id: 'curhatzone',
    name: 'Curhat Zone',
    slug: 'curhatzone',
    description: "Tempat curhat aman. Ga ada yang judge. Probably.",
    avatar_url: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=100&h=100&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&h=400&fit=crop',
    members_count: 389000,
    posts_count: 32000,
    created_at: '2024-05-01',
    is_private: true,
    rules: [
      'Jaga kerahasiaan cerita orang lain — apa yang di-curhat di sini, tetap di sini',
      'Dilarang menghakimi atau memberi solusi yang tidak diminta',
      'Gunakan trigger warning untuk topik sensitif (TW: ...)',
      'Dukung satu sama lain dengan empati, bukan simpati kosong',
      'Dilarang screenshot dan menyebarkan curhat orang lain',
    ],
  },
];
